[package]
name = "roma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm = "0.3.0"
libc = { version = "0.2.140", default-features = false }
libc-print = "0.1.21"